pipeline{
    agent any
    //  tools{
    //     nodejs 'node18'
    // }
    stages {
        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/Lutfar1996/FullStackRepo.git'
            }
        }
        stage('Install Dependencies') {
           script {
                    // Ensure you're in the directory where package.json exists
                    dir('frontend') {  // Replace with the correct directory path
                        sh 'npm install'
                    }
                }
        }
        stage("Docker Build & Push"){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                       sh "docker build -t fullStackfront ."
                       sh "docker tag fullStackfront lutfar1996/fullStackfront:latest "
                       sh "docker push lutfar1996/fullStackfront:latest "
                       sh "docker "
                    }
                }
            }
        }
       
    }
}