apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lutfar1996/backend:4
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: terraform-20241107074145480700000001.cpius0u6u7nc.us-east-1.rds.amazonaws.com # AWS RDS endpoint
            - name: DB_USER
              value: pgadmin # Your DB user
            - name: DB_PASSWORD
              value: Admin123!
            - name: DB_NAME
              value: pgres # Database name
            - name: DB_PORT
              value: "5432" # Default PostgreSQL port

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
