pipeline {
    agent any
    tools{
        nodejs 'node18'
    }
    stages {
        stage('clean workspace') {
            steps {
                cleanWs()
            }
        }
        stage('Checkout from Git') {
            steps {
                git branch: 'main', url: 'https://github.com/Lutfar1996/FullStackRepo.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                script {
                    // Ensure you're in the directory where package.json exists
                    dir('backend') {  // Replace with the correct directory path
                        sh 'npm install'
                    }
                }
            }
        }
        stage('Docker Build & Push') {
            steps {
                script {
                    // Provide Docker registry credentials and ensure it's wrapped in a block
                    withDockerRegistry([credentialsId: 'docker', url: 'https://index.docker.io/v1/']) {
                        dir('backend') {
                            def imageTag = "lutfar1996/backend:${BUILD_NUMBER}"  // Tag the image with the build number
                            sh "docker build -t ${imageTag} ."
                            sh "docker push ${imageTag}"
                        }
                    }
                }
            }
        }
    }
}
