pipeline{
    agent any
    environment {
        // Set Node.js environment for the frontend
        NODE_HOME = tool name: 'NodeJS', type: 'NodeJS'
        DB_HOST = credentials('DB_HOST')  // Fetch from Jenkins Credentials
        DB_USER = credentials('DB_USER')
        DB_PASSWORD = credentials('DB_PASSWORD')
        DB_NAME = credentials('DB_NAME')
        DB_PORT = credentials('DB_PORT')
    }
    stages {
        stage('clean workspace'){
            steps{
                cleanWs()
            }
        }
        stage('Checkout from Git'){
            steps{
                git branch: 'main', url: 'https://github.com/Lutfar1996/FullStackRepo.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh "npm install"
            }
        }
        stage("Docker Build & Push"){
            steps{
                script{
                   withDockerRegistry(credentialsId: 'docker', toolName: 'docker'){   
                       sh "docker build -t fullStack ."
                       sh "docker tag fullStack lutfar1996/fullStack:latest "
                       sh "docker push lutfar1996/fullStack:latest "
                       sh "docker "
                    }
                }
            }
        }
       
    }
}