apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: <your-dockerhub-username>/backend:latest
          ports:
            - containerPort: 5001
          env:
            - name: DB_HOST
              value: <AWS_RDS_HOSTNAME> # Replace with your AWS RDS endpoint
            - name: DB_USER
              value: <AWS_RDS_DB_USER> # Replace with your AWS RDS DB username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rds-secrets
                  key: password
            - name: DB_NAME
              value: <AWS_RDS_DB_NAME> # Replace with your AWS RDS DB name
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  type: ClusterIP
